name: release-fiber-for-wasmedge

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-20.04
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up build environment
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev

      - name: Install Rust v1.66
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.66

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_FIBER_TOKEN }}
        shell: bash
        run: |
          cargo publish --dry-run

      # - name: Publish
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_FIBER_TOKEN }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   shell: bash
      #   working-directory: crates/
      #   run: |
      #       cargo publish
